version: '2'

services:

  # Redis
  redis:
    container_name: "redis-${USER}"
    hostname: redis
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"

  # Minio
  minio:
    container_name: "minio-${USER}"
    hostname: minio
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=trexaccesskey
      - MINIO_SECRET_KEY=trex123321
    ports:
      - "9000:9000"
    volumes:
      - /data/minio/data:/data
    command: "server /data"
