apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.minio.s3
type: Opaque
data:
  # echo -n "${AWS_ACCESS_KEY_ID}" | base64
  # trexaccesskey
  aws_access_key_id: dHJleGFjY2Vzc2tleQ==
  # echo -n "${AWS_SECRET_ACCESS_KEY}" | base64
  # trex123321
  aws_secret_access_key: dHJleDEyMzMyMQ==
  # echo -n "minio-service:9000" | base64
  s3_address: bWluaW8tc2VydmljZTo5MDAw
---
apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.aws.s3
type: Opaque
data:
  # echo -n "${AWS_ACCESS_KEY_ID}" | base64
  aws_access_key_id: SETYOURENCODEDAWSACCESSKEYID
  # echo -n "${AWS_SECRET_ACCESS_KEY}" | base64
  aws_secret_access_key: SETYOURENCODEDAWSSECRETACCESSKEY
  # echo -n "s3.us-east-1.amazonaws.com" | base64
  s3_address: czMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ae.docker.creds
  namespace: default
data:
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # kubectl create secret docker-registry ae.docker.creds --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-password> --docker-email=<your-email>
  .dockerconfigjson: SETYOURDOCKERCREDS
